name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS Region"
        required: true
        default: "us-east-1"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      - run: sam build --use-container --template /home/runner/work/the-wild-oasis-main/the-wild-oasis-main/infrastructure/template.yaml
     
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

      - name: Sync build folder to S3
        run: aws s3 sync ./build s3://the-wild-oasis-web-app-s3-bucket --delete
