name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS Region"
        required: true
        default: "us-east-1"

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: SAM Build
        run: sam build

      - name: SAM Deploy
        run: sam deploy --guided --region ${{ github.event.inputs.aws_region }}

      - name: Sync build folder to S3
        run: aws s3 sync ./build s3://the-wild-oasis-web-app-s3-bucket --delete
